### ISSUE TITLE
GET /v1/vote/article do not return expected number of votes

### ISSUE THREAD

**Issue by siuying** [kaif-open/kaif-api#1]
On one of my test I found when I send a `GET /v1/vote/article` with following parameter:
`@{@"article-id": @"cLstHmXC0H,cJ6eRmAw6n,cbwYNJ2PIb"}` 

I get unexpected result:

```
<__NSCFArray 0x7ff18263b9d0>(
{
    targetId = cbwYNJ2PIb;
    updateTime = "2015-03-18T01:22:55Z";
    voteState = UP;
},
{
    targetId = cLstHmXC0H;
    updateTime = "2015-04-08T05:43:09Z";
    voteState = UP;
}
)
```

It should return exactly 3 records, not two?

**Comment by siuying** [comment]
On a related note, `GET  /v1/vote/debate/article/cLstHmXC0H` will return empty array, which should not be empty.

**Comment by ingramchen** [comment]
vote 的 query 類 API 只會回傳 _自己投過_ 的結果，沒有的資料你可以視為 voteState=EMPTY。畢竟大部份的情況都是沒有投過的。這是為了省無謂的頻寬浪費。

對一個 page 的 article (25 個)，下了一次 batch query，回來的可能是一兩個，因為用戶只過投了一兩個。

對一個 article 裡的討論，query 用戶對所有 Debate 的投票，這個更不可能回傳所有的投票了，因為討論串裡可能有五百個討論，用戶只對兩則討論投過票。回傳500個投票結果是不切實際的 (裡面有 498 個都是 EMPTY)。

所以，vote query 的 API 的行為是：
1. 如果你收到 voteState 是 UP/DOWN，這表示該用戶最後投的結果。
2. 如果你收到 EMPTY，這表示用戶之前投過，後來又反悔，取消過投票。
3. 如果沒收到 voteState，表示用戶完全沒投過。

server 端可以將 EMPTY 都過濾掉，這樣行為比較一致，但其實 2. 的意思和沒投不大一樣。

**Comment by siuying** [comment]
> 只會回傳 自己投過 的結果

原來如此，了解！謝謝
